[package]
name = "borg_the_spire"
version = "0.1.0"
authors = ["Eli Dupree <vcs@elidupree.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0", features = ["derive", "rc"]}
serde_json = "1.0"
rand = "0.7"
rand_xoshiro = "0.4"
ordered-float = "1.0"
arrayvec = "0.4"
